# Generated by Django 4.1.3 on 2022-11-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertise',
            old_name='image_link',
            new_name='imageId',
        ),
    ]
