# Generated by Django 4.1.3 on 2022-11-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=32)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'REJECTED')], default=0)),
                ('category', models.CharField(blank=True, max_length=256, null=True)),
                ('image_link', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
